"""add avatar_pack and other missing tables

Revision ID: bb15882faef4
Revises: 0020_turn_coordinator
Create Date: 2026-08-26 13:36:01.522716
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bb15882faef4"
down_revision: str | None = "0020_turn_coordinator"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("privacy_level", sa.String(length=4), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="staging", nullable=False),
        sa.Column("encryption_key_ref", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("privacy_level IN ('L0','L1','L2')", name="ck_asset_privacy_level"),
        sa.CheckConstraint(
            "state IN ('staging','active','unreferenced','deleting','deleted','quarantined')",
            name="ck_asset_state",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index("ix_asset_hash", "asset", ["content_hash"], unique=False)
    op.create_index("ix_asset_state", "asset", ["state", "created_at"], unique=False)
    op.create_table(
        "avatar_pack",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("archetype", sa.String(length=64), nullable=False),
        sa.Column("engine", sa.String(length=16), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("license", sa.JSON(), nullable=False),
        sa.Column("built_in", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "installed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "engine IN ('static','live2d','vrm','abstract')", name="ck_avatar_pack_engine"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=160), server_default="local-user", nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="50", nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=True),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Float(), server_default="0", nullable=False),
        sa.Column("current_step", sa.String(length=128), nullable=True),
        sa.Column(
            "resource_class", sa.String(length=32), server_default="cpu-small", nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=160), nullable=True),
        sa.Column("error_detail_safe", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','admitted','running','waiting_user','retry_wait',"
            "'cancelling','succeeded','failed','cancelled')",
            name="ck_job_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_job_idempotency", "job", ["idempotency_key"], unique=False)
    op.create_index("ix_job_owner_created", "job", ["owner", "created_at"], unique=False)
    op.create_index("ix_job_status_available", "job", ["status", "available_at"], unique=False)
    op.create_table(
        "asset_derivation",
        sa.Column("parent_asset_id", sa.Uuid(), nullable=False),
        sa.Column("child_asset_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("params_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["child_asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_asset_id", "child_asset_id", "operation"),
    )
    op.create_table(
        "asset_reference",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("owner_kind", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "owner_kind", "owner_id", "role"),
    )
    op.create_table(
        "avatar_instance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner", sa.String(length=160), server_default="local-user", nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("pack_id", sa.String(length=64), nullable=False),
        sa.Column("customization", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("voice_profile_id", sa.String(length=160), nullable=True),
        sa.Column("theme_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','preview','archived')", name="ck_avatar_instance_status"
        ),
        sa.ForeignKeyConstraint(["pack_id"], ["avatar_pack.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_avatar_instance_owner", "avatar_instance", ["owner"], unique=False)
    op.create_table(
        "job_artifact",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("step_name", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("committed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "step_name", "asset_id", "role"),
    )
    op.create_index("ix_job_artifact_asset", "job_artifact", ["asset_id"], unique=False)
    op.create_table(
        "job_step",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), server_default="0", nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed','cancelled')",
            name="ck_job_step_status",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "name", "attempt", name="uq_job_step_name_attempt"),
    )
    op.create_index("ix_job_step_job", "job_step", ["job_id", "created_at"], unique=False)
    op.create_table(
        "persona_avatar_binding",
        sa.Column("persona_id", sa.BigInteger(), nullable=False),
        sa.Column("avatar_instance_id", sa.Uuid(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["avatar_instance_id"], ["avatar_instance.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["persona_id"], ["persona_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("persona_id", "avatar_instance_id"),
    )
    op.create_index(
        "uq_persona_avatar_default",
        "persona_avatar_binding",
        ["persona_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
        sqlite_where=sa.text("is_default = 1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_persona_avatar_default", table_name="persona_avatar_binding")
    op.drop_table("persona_avatar_binding")
    op.drop_index("ix_job_step_job", table_name="job_step")
    op.drop_table("job_step")
    op.drop_index("ix_job_artifact_asset", table_name="job_artifact")
    op.drop_table("job_artifact")
    op.drop_index("ix_avatar_instance_owner", table_name="avatar_instance")
    op.drop_table("avatar_instance")
    op.drop_table("asset_reference")
    op.drop_table("asset_derivation")
    op.drop_index("ix_job_status_available", table_name="job")
    op.drop_index("ix_job_owner_created", table_name="job")
    op.drop_index("ix_job_idempotency", table_name="job")
    op.drop_table("job")
    op.drop_table("avatar_pack")
    op.drop_index("ix_asset_state", table_name="asset")
    op.drop_index("ix_asset_hash", table_name="asset")
    op.drop_table("asset")
    # ### end Alembic commands ###
